### ISSUE TITLE
`neo4jrestclient` should be included in setup.py

### ISSUE THREAD

**Issue by shfong** [ndexbio/ndex2-client#24] opened 2018-11-06 20:49 UTC
I tried installing the latest version of ndex2 via pip today, and importing the package fails because of the following error: "ModuleNotFoundError: No module named 'neo4jrestclient'". Installing `neo4jrestclient` manually solved the problem, but the package should probably be included in the setup file.

**Comment by cthoyt** [comment] 2018-11-06 21:04
I also had this problem

**Comment by agary-ucsd** [comment] 2018-11-06 21:21
Requirement has been removed and a new version pushed to pypi.  It was intended as a new feature for the next release, but has since been cut.

**Comment by coleslaw481** [comment] 2019-01-03 19:58
Looks like this was fixed in 2.0.0.8

**Closed by coleslaw481** 2019-01-03 19:58 UTC
